language: ruby

rvm:
  - "3.0.2"

services:
  - postgresql

before_script:
  - psql -I postgres -c 'CREATE DATABASE chitter_challenge_test'
  - psql -I postgres -c 'CREATE DATABASE chitter_challenge'

script:
  - bundle exec rspec
