language: ruby

rvm:
  - "3.0.2"

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE chitter_challenge_test' -U postgres
  - psql -c 'CREATE DATABASE chitter_challenge' -U postgres

script:
  - bundle exec rspec
